version: "3.9"

services:
  db:
    image: docker.io/library/mariadb:11
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql  # данные БД сохраняются в домашней папке
    networks:
      - nextcloud

  app:
    image: docker.io/library/nextcloud:latest
    container_name: nextcloud_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      # (необязательно) можно добавить:
      # - NEXTCLOUD_DATA_DIR=/var/www/html/data
    volumes:
      - ./nextcloud_data:/var/www/html
      - ${HOME}/data/soft/nextcloud_st_01:/nextcloud_st_01
    networks:
      - nextcloud
    ports:
      - "8090:80"  # rootless может открывать порты >=1024

networks:
  nextcloud:
    driver: bridge

